### ISSUE TITLE
Incorrect PIC reported under SIE

### ISSUE THREAD

**Issue by ivan-w** [SDL-Hercules-390/hyperion-txf#2] opened 2020-01-15 08:55 UTC
Under SIE (z/VM 6.4) When inside a constrained transaction, when performing a backward branch, the ABORTED transaction flag isn't set in the PIC (18 instead of 218). The same problem occurs when an instruction is executed beyond 128 bytes of the TBEGINC instruction.

**Comment by Fish-Git** [comment] 2020-01-15 18:01
> ... the ABORTED transaction flag isn't set in the PIC (18 instead of 218).

I can't recall whether I mentioned this or not, but **_the POPs is a little unclear/contradictory on this matter._**

On page 6-46 in the section **"Transaction-Constraint Exception"** is does indeed say the PIC should be 218:

> The transaction-constraint exception is indicated by a
> program-interruption code of 0218 hex (or 0298 hex if
> a concurrent PER event is indicated). 

but in _"Figure 5-16. Transactional-Execution Classes for Various Program-Interruption Conditions (Part 2 of 3)"_ on page 5-105, for Exception Condition **"Transaction constraint"** it lists the **"Code (Hex)"** as "0018".

Code (hex) 0018 seems more consistent with all of the other program interruption codes that are already defined by the architecture (see lines 1076-1134 of `esa390.h`), so I'm going to believe 0018 over 0218.

I've searched the manual for an explanation of 0218 instead of 0018 and could not find one. I was thinking maybe the 02xx bit was some type of flag or something, but again, I could find nothing in the manual that says that.

Until someone can point to more definitive/convincing evidence that 218 is the right PIC to use, I'm going to stick with PIC 18 instead. It just makes more sense!

> The same problem occurs when an instruction is executed beyond 128 bytes of the TBEGINC instruction.

I'm not sure what 128 bytes has to do with anything. The manual says for constrained transactions that all instructions must be within the same contiguous _**256**_ bytes of storage, but I don't recall seeing anywhere in our code where we're enforcing that. That's something that we still need to address (fix). But 128? Nope.

I'm closing this issue as invalid. If you feel this is incorrect, feel free to re-open it so we can continue to discuss the matter.

Thanks for taking the time to report this, Ivan!

**Comment by ivan-w** [comment] 2020-01-15 18:05
On an IBM manufactured system running z/VM 6.4, when a transaction abort occurs, the PIC reported is X'218'... on hercules it is X'18'....

The 'Transaction Abort Flag' should definitely be set when the PIC (whatever PIC it is if it not filtered) should set the transaction abort flag in the reported PIC.

In the case of a constrained transaction, any condition that cause the constrained transaction to be aborted should specify BOTH that a constrained transaction exception occurred (restricted instruction, condition, etc..) *AND* that a transaction was aborted (the current transaction was aborted).

Now Program interrupt filtering in a constrained transaction makes little sense since the only condition code possible for TBEGINC is 0... (Unlike TBEGIN which allows transactions to take decisions depending on transaction transient conditions using the condition code).

**Comment by ivan-w** [comment] 2020-01-15 18:18
X'200' should *ALWAYS* be set when a transaction is aborted...

The X'18' indicates why (in the case of constrained transaction which meet a specific constrained transaction restriction) - but there could be other conditions (especially in the case on non-constrained transactions).

But if a transaction is aborted, X'200' should always be set. If you are within a constrained transaction, if you issue an instruction that is not supported, the PIC would be X'201' or X'218'.. Setting X'200' is important so that the OS or Hypervisor can accommodate for the fact there was a transaction in progress.

**Comment by ivan-w** [comment] 2020-01-15 18:43
This is described on Page 6-46 and 5-102 in SA22-7832-11...

Basically any condition that causes a transaction to be aborted and generate a program interrupt to occur MUST set X'200'! (It may or may not also be set in any explicit (as specified in TBEGIN) or implicit TDB (X'1800' in real storage available for both TBEGIN and TBEGINC) - I haven't looked that far).

**Comment by ivan-w** [comment] 2020-01-15 18:51
It is a bug and is not invalid (IMHO).

**Comment by ivan-w** [comment] 2020-01-15 18:55
Samples: 

**IBM System:**
```
txft005
PERFORMING BACKWARD BRANCH IN CONSTRAINED MODE. 
 -> 00000000000131C2   BCT     4610C1BE    000131BE
*TN 00000000000131B4       PROG    0218 -> 00013206
        TRANSACTION ABORT + TRANSACTION CONSTRAINT
CONSTRAINED TRANSACTION EXCEPTION RAISED. 
```

**Hercules:**
```
txft005
PERFORMING BACKWARD BRANCH IN CONSTRAINED MODE.
 -> 000000000008F1AE   O       56F0C31C    0008F31C
*** 000000000008F1AE       PROG    0018 -> 0008F206
              TRANSACTION CONSTRAINT
UNEXPECTED PIC 0018.
```

That's where I say.. Hmm.. Something is amiss! &nbsp; `;-)`

-Ivan

**Comment by ivan-w** [comment] 2020-01-15 18:59
Also other things look wrong.. The IBM system clearly indicates the Constrained Transaction restriction is the BCT... Hercules indicates some other portion of the code... Weird...

PS : I did a z/VM "TRACE PROG"... this does NOT set PER (it just tells SIE to intercept program interrupts so that CP can report the event). When doing a PER trace under z/VM 6.4 a whole other chain of events happen... and I haven't tried that yet.

**Comment by Fish-Git** [comment] 2020-01-15 22:27
(combined reply)

Ivan wrote:

> On an IBM manufactured system running z/VM 6.4, when a transaction abort occurs, the PIC reported is X'218'... on hercules it is X'18'....

> Basically any condition that causes a transaction to be aborted and generate a program interrupt to occur MUST set X'200'!

> This is described on Page 6-46 and 5-102 in SA22-7832-11...

That's what I was saying! There _appears_ to be a discrepancy/contradiction regarding what the PIC should be for an aborted transaction! In SA22-7832-12 (not 11), the pages I mentioned are almost identical to the pages _you_ mentioned! 6-46 and 5-105!

But no nevermind. I _**finally(!)**_ found what I was looking for in _"Figure 6-1: Interruption Action"_ on page 6-3 and 6-4! In the Interruption Code column of that table, the X'200' bit (flag) you keep mentioning (that earlier I couldn't find any mention of, but that was probably because I was searching for the wrong thing!) has a 't' in that bit position, with 't' defined at the end of the table/figure as being "Transactional-execution-aborted event"!

So you're right! We most definitely _should_ be setting the x'200' bit (which before now I didn't even know existed!) whenever a transaction is aborted. My bad. I'll try to get that fixed.

> Samples:
> 
> **IBM System:**
> [...]
> 
> **Hercules:**
> [...]
> 
> That's where I say.. Hmm.. Something is amiss!   `;-)`

No shit! &nbsp; `:)`

> Also other things look wrong.. The IBM system clearly indicates the Constrained Transaction restriction is the BCT... Hercules indicates some other portion of the code... Weird...

Yeah. Something is obviously wrong somewhere... (sigh) &nbsp; `:(`

Let me try to dig into it.

> It is a bug and is not invalid (IMHO).

Agreed 100%. I've reopened the issue. My apologies for closing it in the first place, but at the time I hadn't been able to locate any mention or explanation of this x'200' flag! I _tried and tried and TRIED_ looking for it, but kept coming up empty (and I wasn't about to start reading the entire freaking manual from beginning to end!). It wasn't until JUST NOW, in response your comments in this GitHub Issue, that I was then able to _FINALLY_ locate that damn x'200' flag!

So yeah, the issue has now been re-opened, as it most definitely is a bug.

Thank you for your patience with my periodic incompetence. &nbsp; `:(`

**Comment by ivan-w** [comment] 2020-01-16 01:07
> Thank you for your patience ...

That's what we do! We create and we fix stuff! (Except for me: I intentionally hit on stuff until it breaks, but that's my job).

**Comment by Fish-Git** [comment] 2020-01-16 17:31
> I intentionally hit on stuff until it breaks.

And you're damn good at it too! &nbsp; `:)`

(which is good!)

**Comment by ivan-w** [comment] 2020-01-16 18:16
One thing to remember (just for the record).. the Program Old PSW when in a non-constrained transaction is the instruction that follows the TBEGIN (or TBEGINC if Transaction depth > 1).. So that a LPSWE will get you right behind the TBEGIN/TBEGINC instruction with the correct CC.. If it is a constrained transaction (TBEGINC depth 1) it is the address of the TBEGINC instruction itself (most probably with an ILC of 0 for both cases) so that the transaction can be restarted. (Transaction Execution Facility is one of the weirdest thing I ever came up with in any Instruction architecture!)

**Comment by Fish-Git** [comment] 2020-01-17 07:27
@ivan-w

Should hopefully be fixed now by commit f060e5317cf82def45cacacee9fb407696adc19e. Please try your `txft005` again. Thanks.

Will await your confirmation before closing.

**Comment by ivan-w** [comment] 2020-01-17 11:53
```
HHC01413I Hercules version 4.3.9999.0-SDL-gf060e531 (4.3.9999.0)
HHC01414I (C) Copyright 1999-2019 by Roger Bowler, Jan Jaeger, and others
HHC01417I ** The SoftDevLabs version of Hercules **
HHC01415I Build date: Jan 17 2020 at 12:31:07
```

```
txft005
PERFORMING BACKWARD BRANCH IN CONSTRAINED MODE.
 -> 000000000008F1AE   O       56F0C31C    0008F31C
*** 000000000008F1AE       PROG    0018 -> 0008F206
              TRANSACTION CONSTRAINT
UNEXPECTED PIC 0018.
Ready(00002); T=0.01/0.01 08:52:42
```

Crapola...

**Comment by ivan-w** [comment] 2020-01-17 11:56
The old PSW should be related to the TBEGIN (+4) and TBEGINC(+0 unless already in a transaction) and the address of the offending instruction set in the TDB. Without the X'200' indicator the supervisor/hypervisor cannot know the actual failing instruction is shown in the TDB.

**Comment by Fish-Git** [comment] 2020-01-17 18:57
> Crapola...

Crapola is right. &nbsp; `:(`

> The old PSW should be related to the TBEGIN (+4) and TBEGINC (+0) unless already in a transaction) and the address of the offending instruction set in the TDB. Without the X'200' indicator the supervisor/hypervisor cannot know the actual failing instruction is shown in the TDB.

I know that.

The abort PSW is being calculated and saved in the `process_tbegin` function:

https://github.com/SDL-Hercules-390/hyperion-txf/blob/f060e5317cf82def45cacacee9fb407696adc19e/transact.c#L524-L531

and moved into the current PSW by the `abort_transaction` function when an abort occurs:

https://github.com/SDL-Hercules-390/hyperion-txf/blob/f060e5317cf82def45cacacee9fb407696adc19e/transact.c#L739-L744

When the actual program interrupt occurs (at the end of the `abort_transaction` function):

https://github.com/SDL-Hercules-390/hyperion-txf/blob/f060e5317cf82def45cacacee9fb407696adc19e/transact.c#L884-L891

the cpu.c `program_interrupt` function is of course then called, which _should_ then turn on the X'200' flag (`PGM_TXF_EVENT`) in the interrupt code:

https://github.com/SDL-Hercules-390/hyperion-txf/blob/f060e5317cf82def45cacacee9fb407696adc19e/cpu.c#L517-L535

which then gets stored into low core, as well as copied into the TDB piid field:

https://github.com/SDL-Hercules-390/hyperion-txf/blob/f060e5317cf82def45cacacee9fb407696adc19e/cpu.c#L1015-L1035

so I don't know why it's still showing the exception code without the X'200' flag. It's clearly being set!

As far as the incorrect failing instruction address being reported in the TDB is concerned (TDB struct field `tdbinstaddr`), it's also being set by the `abort_transaction` function to whatever instruction the current PSW is pointing to whenever the abort occurs:

https://github.com/SDL-Hercules-390/hyperion-txf/blob/f060e5317cf82def45cacacee9fb407696adc19e/transact.c#L693

https://github.com/SDL-Hercules-390/hyperion-txf/blob/f060e5317cf82def45cacacee9fb407696adc19e/transact.c#L820

https://github.com/SDL-Hercules-390/hyperion-txf/blob/f060e5317cf82def45cacacee9fb407696adc19e/transact.c#L850

So I don't know why that's wrong either. &nbsp; `:(`

I obviously missed _something_ somewhere, but I don't know what!

HELP! &nbsp; `:(`

**Comment by ivan-w** [comment] 2020-01-29 09:47
I have an idea... Need to test it.

**Comment by Fish-Git** [comment] 2020-01-29 19:31
> I have an idea... Need to test it.

Me too! &nbsp; `:)`

**Closed as completed** 2020-01-30 09:00 UTC
Labels: bug

**Comment by Fish-Git** [comment] 2020-01-30 10:07
@ivan-w

Ivan,

More than one of those TXF00n tests of yours are bad.

**TXFT005** for example ("Performing Backward Branch in Constrained Mode") fails because only _relative_ type branch instructions are allowed in constrained transaction mode, and your test is using a `BCT` instruction, which causes a constraint exception, which in turn causes your test to erroneously believe it has successfully passed. Your test however, _thought_ it was testing the "no-backward-branches" constraint but in _actuality_ was simply testing the "non-relative-branch instructions are not allowed" constraint!

Your **TXFT006** test ("Executing Instructions Beyond 256 Bytes") is failing for the same reason: it's using a non-relative unconditional `B` branch instruction which, as explained, is verboten in constrained mode. Thus the test is erroneously passing because your test expects a constraint exception to occur (which it does!), but it's not occurring for the right reason. Your test thinks it's because it branched beyond 256 bytes (which is a constraint that our TXF code isn't even enforcing yet!), but it _actually_ failed because it simply executed an instruction which is restricted in constrained mode.  So once again you are not actually testing what you _think_ you're testing!

Because fixing such bugs necessarily requires writing one or more MACROs to support one or more z/Arch instructions (mnemonics) like you've already done for several other instructions (because of the CMS assembler's shortcoming of not supporting/understanding the z/Arch instruction set), I decided to toss your tests aside and to write my own SATK/ASMA standalone `loadcore' versions of all of your tests instead, so that _now,_ except for the TXFT006, _ALL_ tests pass.

That's in stand-alone `loadcore` mode though.

Under z/VM in SIE mode however, all tests except for 6 _and 7_ now pass.  TXFT006 of course fails for the same reason as before: it's testing a constraint we don't yet enforce.  Test **TXFT007** however ("Executing more than 32 instructions"), fails for some as-yet unknown reason. It passes in stand-alone non-z/VM non-SIE mode, but is failing when run under z/VM in SIE mode. That's the only test I haven't figured out how to fix yet.

**PLEASE NOTE** that the tests I am running under z/VM are the _exact same **`loadcore`** tests_ as the ones mentioned above. They are _not_ your original CMS tests. They are my fixed `loadcore` equivalents of your tests.

I decided it was much easier for me to build such tests thanks to **[Harold Grovesteen's _most excellent_ SATK/ASMA product](https://github.com/s390guy/SATK)**. I highly recommend using it.  It totally rocks and was written for _exactly_ such purposes: to make writing Hercule test cases _trivially_ easy. Give it a try!

Now you may of course be asking yourself (or maybe you're not, I don't know!), how can Hercules `loadcore` tests be run under z/VM? (CMS?)

Well, as you may (or may not!) remember, a while back I created a "LOADCORE MODULE" for CMS which loads a Hercules binary "loadcore" file into your virtual machine's low core and "runs" it (via CP RESTART). I wrote it a while ago while trying to research [Moshix's "Slow DASD Formatting Under z/VM" issue](https://github.com/SDL-Hercules-390/hyperion/issues/201).  It allows you to run any given Hercules "loadcore" test under Z/VM CMS _in the **exact same way**_ that the Hercules `loadcore` and `restart` commands do: it reads the specified binary file (fn ft fm) into the virtual machine's low core and then issues a CP RESTART to run the test. This ensures the _exact same thing_ is being tested in the _exact same way_ in both places. This is important IMO.

Your tests can only be run under CMS, but not stand-alone outside of CMS.  _(and have problems besides)_

My tests on the other hand can run _**unmodified**_ in _either_ environment. _(and actually work as intended)_

My way is better. &nbsp; `;-)`

Oh! And when I say all tests now pass (except for the two mentioned: 6 will always fail until we add code to enforce that particular constraint, and 7 currently only passes in stand-alone mode but fails when run under z/VM SIE), that means just that: the tests that were failing because they were getting a PIC 18 instead of a PIC 218 now pass. I beat you to the punch with getting the missing 200 flag fixed! (i.e. this very GitHub Issue you're reading). Ha! Ha! Nyah! Nyah! &nbsp; `;-)`

_____________

Downloadable files:

* [**LOADCORE ASSEMBLE**](https://github.com/Fish-Git/hyperion-fish-txf/files/4133368/LOADCORE.zip) (see source file comments for how to build/use).
* [**zip of my stand-alone SATK/ASMA versions of your TXFT00<i>n</i> tests.**](https://github.com/Fish-Git/hyperion-fish-txf/files/4133397/TXFT00n.CORE.zip)


Questions? Problems? Concerns? Contact me! (or just comment in this github issue thread)
